# Copyright (C) 1998-2018 by the Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

"""Parse bounce messages generated by Postfix.

This also matches something called `Keftamail` which looks just like Postfix
bounces with the word Postfix scratched out and the word `Keftamail` written
in in crayon.

It also matches something claiming to be `The BNS Postfix program`, and
`SMTP_Gateway`. Everybody's gotta be different, huh?
"""

import re
from typing import List, Optional, Tuple, Union
from email.message import Message
import io

# Matches the standard Postfix bounce template
postfix_pattern = re.compile(r"""
    ^Transcript[ ]of[ ]session[ ]follows
    .*?
    while[ ]talking[ ]to[ ](.*?):
    """, re.VERBOSE | re.DOTALL)

# Matches the standard Postfix error template
error_pattern = re.compile(r"""
    ^The[ ](?:BNS[ ])?Postfix[ ](?:program|(?:SMTP[ ]server))
    .*?
    said:[ ](.*)
    """, re.VERBOSE | re.DOTALL)

# Matches the Keftamail error template
keftamail_pattern = re.compile(r"""
    ^The[ ]Keftamail[ ]program
    .*?
    said:[ ](.*)
    """, re.VERBOSE | re.DOTALL)


def flatten(msg: Message, leaves: List[Message]) -> None:
    """Extract all non-multipart submessages.
    
    Args:
        msg: The message to process
        leaves: List to store non-multipart submessages
    """
    if msg.is_multipart():
        for part in msg.get_payload():
            flatten(part, leaves)
    else:
        leaves.append(msg)


def process(msg: Message) -> Optional[List[Tuple[str, str]]]:
    """Extract bouncing email addresses from a Postfix bounce message.
    
    Args:
        msg: The bounce message to process
        
    Returns:
        A list of (email, error) tuples for each bouncing address,
        or None if this is not a recognized bounce format
    """
    leaves = []
    flatten(msg, leaves)
    
    # Postfix bounces must contain a message/delivery-status part
    if not any(part.get_content_type() == 'message/delivery-status' 
              for part in leaves):
        return None
        
    # Get the message content
    try:
        content = msg.get_payload(0).get_payload(0).get_payload(decode=True)
        if isinstance(content, bytes):
            content = content.decode('utf-8', 'replace')
    except (AttributeError, IndexError):
        return None
        
    # Look for postfix patterns
    mo = postfix_pattern.search(content)
    if not mo:
        mo = error_pattern.search(content)
    if not mo:
        mo = keftamail_pattern.search(content)
    if not mo:
        return None
        
    # Extract the failing addresses and errors
    bounces = []
    for line in content.splitlines():
        line = line.strip()
        if not line:
            continue
            
        # Skip informational messages
        if line.startswith('Messages') or line.startswith('Delivery'):
            continue
            
        # Extract email and error
        parts = line.split(':', 1)
        if len(parts) != 2:
            continue
            
        email = parts[0].strip()
        error = parts[1].strip()
        
        # Skip if no valid email found
        if not '@' in email:
            continue
            
        bounces.append((email, error))
        
    return bounces if bounces else None
